"""
Patches missing image URLs into towing-data.js using CURT's PIES image export.

towing-data.js was generated by 05_LEGACY_CONVERSION_SCRIPTS/convert-curt.ps1
from a flat CSV whose "Primary Image" column was empty for ~99.7% of rows.
CURT's full PIES image feed (08_MISC_DATA/curt towing produc data -imges/
CUR20260222_PIESImage72.txt) has real photo URLs for far more part numbers —
this script joins that in without touching fitment/pricing data.

Each row lives on its own line (one JS array literal per line), so this
patches the trailing `,null]` image field directly rather than re-parsing
the whole array.

Usage: python tools/patch-curt-images.py
"""
import re

PIES_IMAGE_FILE = r"C:\Users\James\Desktop\MY WEB APP PROJECTS\08_MISC_DATA\curt towing produc data -imges\CUR20260222_PIESImage72.txt"
TOWING_DATA_JS = r"C:\Users\James\Desktop\MY WEB APP PROJECTS\github-repo\cloudflare\towing-data.js"

# Real product photos only, best angle/resolution first. Excludes FAB (feature
# badges), DRW (dimension drawings), INS (instructions), RGL (regulatory
# labels), ZZ3 (logos), BUL (bullet text).
ASSET_PRIORITY = ['P04', 'P06', 'P07', 'P02', 'P01']

PART_NUM_RE = re.compile(r'^\["CURT","(?:[^"\\]|\\.)*","([^"]*)"')
NULL_IMG_RE = re.compile(r',null\](,?)\s*$')

def build_image_map():
    by_type = {t: {} for t in ASSET_PRIORITY}
    with open(PIES_IMAGE_FILE, encoding='utf-8', errors='replace') as f:
        next(f)  # header
        for line in f:
            cols = line.rstrip('\n').split('|')
            if len(cols) < 7:
                continue
            part_num, asset_type, url = cols[1], cols[2], cols[6]
            if asset_type in by_type and part_num not in by_type[asset_type] and url.startswith('http'):
                by_type[asset_type][part_num] = url
    image_map = {}
    for t in reversed(ASSET_PRIORITY):  # lowest priority first, highest overwrites
        image_map.update(by_type[t])
    return image_map

def main():
    image_map = build_image_map()
    print(f"Built image map: {len(image_map)} part numbers with a real photo")

    with open(TOWING_DATA_JS, encoding='utf-8-sig') as f:
        lines = f.readlines()

    total = 0
    patched = 0
    missing = set()

    for i, line in enumerate(lines):
        m = PART_NUM_RE.match(line)
        if not m:
            continue
        total += 1
        nm = NULL_IMG_RE.search(line)
        if not nm:
            continue  # already has an image
        part_num = m.group(1)
        if part_num in image_map:
            trailing_comma = nm.group(1)
            new_ending = ',"' + image_map[part_num] + '"]' + trailing_comma + '\n'
            lines[i] = line[:nm.start()] + new_ending
            patched += 1
        else:
            missing.add(part_num)

    print(f"Rows scanned: {total}")
    print(f"Rows patched: {patched}")
    print(f"Distinct part numbers still missing a photo: {len(missing)}")

    with open(TOWING_DATA_JS, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    print("Wrote", TOWING_DATA_JS)

if __name__ == '__main__':
    main()
